spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://roundhouse.proxy.rlwy.net:58891/railway
    username: root
    password: 4GcH6h2CeG1bBfHh3egcHbbgFdC5hbEb
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    open-in-view: true
    mail:
      host: smtp.gmail.com
      port: 587
      username: empresa.comvol@gmail.com
      password: fvqnrchwgxaqfbcp